// <auto-generated />
namespace MvcMovie.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ratunek : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ratunek));
        
        string IMigrationMetadata.Id
        {
            get { return "201301161832084_ratunek"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
